[project]
id = "culturepassport-dev"

[api]
port = 54321
schemas = ["public"]

[db]
port = 54322

[studio]
port = 54323

[auth]
site_url = "http://localhost:5173"
additional_redirect_urls = ["http://localhost:5173"]
jwt_expiry = 3600
enable_signup = false
